= EB Corbos StarterKit 安装说明

== 解压安装包
....
mkdir -p /tmp/delivery
cd /tmp/delivery
tar xf ~/Downloads/adg-eblinux-standard-delivery.tar.gz
....

== 准备环境
....
./adg-standard-installer-ADG-2.2.sh
....
路径建议使用默认路径 ~/ara/eb

== 安装corbos
在安装之前需要在~/.bashrc最后一行添加如下环境变量：
....
export workspace=~/ara/eb/workspace/
....
执行命令：
....
ara-cli SdkMgr --overwrite --activate --update-packages adg.*.tar.gz
....
在最后可根据自己的当前环境选择相应的 `platform:` 比如`qemu-x86` 

== 运行corbos
....
corbos-studio-launcher --target-os eblinux
....
点击图标可执行程序路径： ~/ara/eb/tools/studio/ADG-2.2/EB_corbos_Studio
选择一个自己的workspace路径，下面我的workspace路径为：~/ara/eb/workspace

== 准备adg demo
adg demo路径为： ~/ara/eb/adaptivecore/source/git/ara_Demos/impl/demonstrator/templates/demos/
把5个demos拷贝进workspace。我放在workspace/adg/demo下

== 根据所给的demo创建工程
以Sensor_Preprocessor为例：
ara-cli Application --generate-cmake --app ~/ara/eb/workspace/adg/demo/Sensor_Preprocessor/ --target-os eblinux --target-platform qemu-x86 

== 导入工程
import->工程路径
Browser选择自己workspace路径。
Copy project into workspace选项在项目不在workspace目录的时候需要选中。

目录结构介绍：
Build Targets里面是一些编译操作
Includes是依赖的第三方头文件和我们ADG的头文件
Impl是我们需要实现功能的代码路径
Launch是ContainerDeploy到qemu之后，提供run和debug操作
Model放的是该工程依赖ADG的arxml配置文件
Plugets里的插件可以让我们根据model里的arxml生成配置文件或者代码，具体可以看user guide
Test里放的是单元测试代码
…

== 运行与ADG相关的pluget,或者corbos点击plugets--下的插件
Dataprocessor，SensorManager，Sensor_handler需要PM插件
注意：
跨VM的Sensor_handler和Preprocessor需要ComManifest插件
必要插件：EM, ComBinding
还有Sensor_handler和preprocessor最后需要点一下Build Target/Deploy Target File,
之后可以在qemu1和qemu2  之间通信。

=== 命令行操作：
--EM相关—
ara-cli RunPluget --name araEmManifestGen.pluget \
--input  ~/ara/eb/workspace/adg/demo/Sensor_Preprocessor/ \
--output ~/ara/eb/workspace/adg/demo/Sensor_Preprocessor/
--Com相关—
ara-cli RunPluget --name AraComBindingGenerator.pluget \
--input  ~/ara/eb/workspace/adg/demo/Sensor_Preprocessor/ \
--output  ~/ara/eb/workspace/adg/demo/Sensor_Preprocessor/
--Com配置文件—
ara-cli RunPluget --name AraComManifestGenerator.pluget \
--input  ~/ara/eb/workspace/adg/demo/Sensor_Preprocessor/ \
--output  ~/ara/eb/workspace/adg/demo/Sensor_Preprocessor/
--PM相关—
ara-cli RunPluget --name araPmManifestGen.pluget \
--input  ~/ara/eb/workspace/adg/demo/Sensor_Preprocessor/ \
--output  ~/ara/eb/workspace/adg/demo/Sensor_Preprocessor/
…
=== Ui界面操作：
==== 执行AraComBindingGenerator.pluget,点击OK
会在generated文件夹下生成代码，给Service或Client使用。

==== 执行AraComManifestGenerator.pluget,点击OK
会在generated下生成config文件夹，里面有sensor_preprocessor_someip_machine1.json，在deploy container之后，执行Build Targets/DeployTargetFiles时会把该json文件deploy到qemu里/etc/adaptive/ara_Com/daemon_1/sensor_preprocessor_someip_machine1.json。com_daemon可能需要重启，可以执行
ps ww | grep com_daemon 
查看com_daemon是否把该配置文件加上。如果没有需要执行
systemctl restart com-daemon-container

==== 执行araEmManifestGen,点击OK
会在generated文件夹生成EM相关的配置文件

== 编译工程/或者corbos点击Build Targets/Build
ara-cli Application --app  ~/ara/eb/workspace/adg/demo/Sensor_Preprocessor/ --target-os eblinux --target-platform qemu-x86
== 把编译好的工程封装进Container/或者corbos点击Build Targets/CreateAppContainer
ara-cli CreateAppContainer --app-dir  ~/ara/eb/workspace/adg/demo/Sensor_Preprocessor/ \
--config-dir  ~/ara/eb/workspace/adg/demo/Sensor_Preprocessor/generated \
--container-dir  ~/ara/eb/workspace/adg/demo/Sensor_Preprocessor/container

== 起qemu1
数字1代表qemu1.
ara-network -a -N 1
ara-cli RunQemu --start 1 --target-os eblinux

=== 登陆qemu1
ssh -o StrictHostKeyChecking=no root@fd00::eb:1
== 部署container到qemu1
ara-cli DeployAppContainer --app-dir  ~/ara/eb/workspace/adg/demo/Sensor_Preprocessor/ --target-host root@fd00::eb:1
注意：执行到这一步后需要相同步骤把Sensor_Manager，Sensor_dataProcessor，Display_Manager Sensor_handler部署到qemu上。
在部署Sensor_handler时需要修改--target-host root@fd00::eb:2
== 执行程序
runc list #查看已经运行container
Qemu1:
Qemu2:

=== 命令行操作：
Qemu1:
runc exec Sensor_Preprocessor /opt/Sensor_Preprocessor/bin/Sensor_Preprocessor
runc exec Sensor_Manager /opt/Sensor_Manager/bin/Sensor_Manager
runc exec Sensor_dataProcessor /opt/Sensor_dataProcessor/bin/Sensor_dataProcessor
runc exec Display_Manager /opt/Display_Manager/bin/Display_Manager
Qemu2:
runc exec Sensor_handler /opt/Sensor_handler/bin/Sensor_handler
左1：Displayer_Manager
左2：Sensor_Manager
左3：Sensor_dataProcessor
右1：Sensor_Preprocessor，在Sensor_handler没起之前,FindService结果为0，否则为1
右2：Sensor_handler

=== 界面操作：
点击yes

右击/launch/Sensor_Preprocessor_run.launch -> Run As -> Sensor_Preprocessor_run
会在Console看到程序的log.

== 停止qemu1
ara-cli RunQemu --stop 1



