[[Valeria]]
=== Valeria - 构建完整EB xelor软件包

EB xelor附带名为"Valeria"的构建工具，支持为不同的SoC构建对应的EB xelor软件包。
Valeria封装了Conan命令的调用，通过单一指令方便用户构建xelor软件。
EB xelor包含拥有不同属性的Conan包集合，例如运行在A5x这样性能核上的EB corbos Linux，运行在R7这样实时核上的RT_RefApp，直接运行在CPU上的固件，运行在EB corbos Linux上的EB corbos AdaptiveCore。
Conan可以根据定义在profiles中的设置或选项，进行不同属性的处理。
EB xelor项目包含很多不同属性的包，如果想获取所有需要的包，每次都需要调用很多次Conan命令，Valeria则简化了这个过程，通过读取对应manifest中的构建信息，调用相应的Conan指令。

==== Basic idea
Valeria首先调用 `conan export` 获得所有的EB xelor recipes，保证Conan知道如何构建所有包。然后调用 `conan install --build` 开始构建。最后，它会上传这些Conan包到远程仓库，例如Arifactory。

为了保证正确地构建对应平台的包，Valeria使用 https://docs.conan.io/en/latest/reference/profiles.html#build-profiles-and-host-profiles[conan build and host profiles]。

细节请参考后续章节。

==== Build manifest

Manifest文件描述了哪些包需要构建，如何构建这些包等信息。

对于R-Car H3，我们定义了两个manifest文件
....
config/valeria/r-car-h3/manifests/buildmanifest_linuxbuild.xml
config/valeria/r-car-h3/manifests/buildmanifest_windowsbuild.xml
....
如果是S32G，则是
....
config/valeria/s32g/manifests/buildmanifest_linuxbuild.xml
config/valeria/s32g/manifests/buildmanifest_windowsbuild.xml
....

`buildmanifest_linuxbuild.xml` 代表Valeria会根据这个manifest文件在Linux环境中构建Conan包，与之对应的，`buildmanifest_windowsbuild.xml` 代表需要在Windows环境构建的manifest。

对于每一个包，都需要定义一套host和huild profiles。
例如，`config/valeria/s32g/manifests/buildmanifest_linuxbuild.xml` 中 `u-boot` 信息:
....
        <ComponentBuildSpec>
            <BuildProfile>build/linux_x86_64</BuildProfile>
            <HostProfile>host/A53</HostProfile>
            <HostProfile>host/gcc7_arm64</HostProfile>
            <Recipe>eb_u-boot</Recipe>
        </ComponentBuildSpec>
....
`u-boot` 在Linux x86_64环境中构建，运行在S32G SoC的A53核上。
因此我们定义BuildProfile为 `build/linux_x86_64`，HostProfile则是 `host/A53`。
我们还会用到gcc-linaro编译器来构建 `u-boot`，所以我们还需要定义一个HostProfile为 `host/gcc7_arm64`。

Profiles位于 `config/valeria/r-car-h3/profiles`（R-Car H3） ，`config/valeria/s32g/profiles`（S32G）。

需要注意的是，并非所有recipes都会定义在这个manifest文件中，你只需要列出依赖链上起始recipe。
Conan会构建 `requires` 或 `build_requires` 列出的recipe。
例如:

* EB corbos Linux并没有列出来，因为它是Hypervisor的构建必须项，Linux镜像会是Hypervisor包的一部分
* the compiler required for building the u-boot is not listed, as it is a build requirement of the u-boot.

作为依赖项的Profile，Conan会自动读取它们。
例如构建firmware，需要用到gcc-linaro编译器，我们也会在manifest中指定firmware在linux环境中构建，Conan会知道需要先构建gcc-linaro。

==== 从其他channel拷贝包
类似于在git的某个branch上工作，你可以创建你自己的Conan channel来添加新功能。
例如，EB xelor团队为每一个git分支都有对应名为merge-EBCORE-<jira-id>的channel。
为了重用主开发分支的包，当你使用 `--conan-copy-ref <ref_user>/<ref_channel>:<ref_repo>` 命令时，Valeria会拷贝这些包到你的临时channel。
在你构建之前，Valeria会在 `ref_user` 和 `ref_channel` 中搜索 `ref_repo` 包，如果找到了相同的RREV以及Package ID, Valeria 会下载到本地缓存，拷贝到你的user/channel中。
由于已经有了包，Conan不会再构建这些包。当你在自己的channel第一次构建，或者将master的改动merge到你的分支中时，这个选项对你会很有用。

==== 构建需求的处理
Conan假定 https://docs.conan.io/en/latest/devtools/build_requires.html[build requirement]的改动并不会影响使用它的人最终生成的包。
例如，当构建需求主要是CMake这样的构建工具时，就很有意义。
当然，像编译器这样的构建需求，肯定会有直接影响。
Conan文档推荐在相关recipe中定义并声明特定的设置或选项，使它在计算package ID时产生影响。
例如，编译器版本 `compiler.version` 会影响package ID的计算.
新的编译器会导致产生一个新的package ID，即使使用了 `missing` 选项，还是会触发rebuild。

This strategy is different compared to non-build requirements declared in Conan recipes.
Here, Conan directly includes the requirements' version, and other properties in the Package ID calculation, without having to define an additional setting.
更多信息请参考 https://docs.conan.io/en/latest/creating_packages/define_abi_compatibility.html[Conan package ABI compatibility].

While it usually makes sense to treat build requirements like Conan does, it might be an issue for continuous integration, where you want to have fast verifications of the changes a developer made.
This means that you want to rebuild only packages which are somehow affected by a developer's change.
Thus, continuous integration system would typically use a build policy like `missing`.
Additionally, in merge verification builds you might want to use the channel copy functionality in order to speed up verifications after a rebase from another branch.

In EB xelor, most packages have build requirements that directly change the produced binaries.
例如, `RT_RefApp` demo是依赖于EB tresos AutoCore产品的，也就是说你可以通过Conan设定来解决构建需求的问题，但当你每次想rebuild的时候，你都需要手动更改设定。

为了解决这个问题，当使用 `--build <policy>` build policy时， Valeria通过以下方式处理构建需求:

After exporting all local recipes into the Conan cache, Valeria walks through every dependency tree it can find in the build specifications.
It checks for each build requirement, if there is a package with the same name, version, user, channel, recipe revision, and package ID available in the local cache, or in the specified remote repository.
If Valeria does not find any package, it forces a rebuild of the build requirement, and all of its consumers, as it assumes that any change in a build requirement changes the consuming packages.

Note, that this is not relevant if you do not provide a build policy via command line option `--build`, because then Conan always builds every package.

==== Packages that deploy files
Most of the prebuilt Conan packages for EB xelor contain build artifacts (firmware binaries, filesystem images, etc.) which are collected in package's Conan recipe `package()` method.
When this type of package is installed, it will copy package artifacts to the user space, according package's Conan recipe `deploy()` method.
EB xelor uses Conan's package deploy feature to get package contents available for the users and test systems.

When Valeria build is invoked, it builds and installs the packages.
Each installed package deploys contents to `build/deploy/buildspec-x` folder, where `x` is the number of build specification (from build manifest) which contains the package.

When invoking Valeria build again (rebuilding) and if the `build/deploy` folder is not empty, Valeria stops the build and gives warning.
When you invoke Valeria with option `-cdd` /  `--clean-deploy-dir`, it will automatically clean the `build/deploy` folder before (re)building.

==== 如何调用Valeria
Valeria是一套python脚本，位于：
....
tools/valeria/valeria.py
....
不输入任何参数时，Valeria会显示帮助列表。

Valeria会在调用的目录下建立 `build` 子目录。
在这个目录下，Valeria安装Conan包，为每一个构建细则生成三个Conan lockfile。

===== Lockfiles
lockfiles命名规则如下:
`valeria-buildspec-<number>-<step>.lock`. `number` 代表build manifest中构建细则的位置。
lockfiles有如下这些 `step`:

* `valeria-buildspec-<number>-init.lock`:
在执行 `conan install` 之前，利用 `lock create` 命令生成。它包含构建细则中除了包版本信息的完整依赖树。
Valeria将这个文件作为执行 `conan install` 动作的输入信息。
这个文件包含构建需求信息。
* `valeria-buildspec-<number>-inst.lock`:
它是 `conan install` 命令的输出.
它包含构建的包的完整版本信息。
Additionally, each built Conan package has a 'modified' entry.
* `valeria-buildspec-<number>-full.lock`:
在执行 `conan install` 之后，利用 `lock create` 命令生成。
它包含构建或下载的包的完整版本信息。

===== Linux
本节描述了如何为Renesas R-Car H3和NXP S32G构建完整EB xelor包。 
以NXP S32G为例，如果你想构建H3, 只需要将 `s32g` 替换为 `r-car-h3`。 

假设源代码在：
....
/workdir/EBxelor-2020.12
....
构建的输出文件在：
....
/workdir/valeria/s32g
....

执行以下命令：
....
mkdir -p /workdir/valeria/s32g
cd /workdir/valeria/s32g
/workdir/EBxelor-2020.12/tools/valeria/valeria.py -b missing -M build \
-m /workdir/EBxelor-2020.12/config/valeria/s32g/manifests/\
buildmanifest_linuxbuild.xml \
-p /workdir/EBxelor-2020.12/config/valeria/s32g/profiles \
-r /workdir/EBxelor-2020.12/pkg \
-cr eb_core-devdrops \
-ccr EBxelor/2020.12:eb_core-releases \
-cdd \
your_user valeria-test
....
以上命令中出现的选项：

* `-b missing -M build`: this instructs Valeria to build the packages and use the Conan build policy `missing`. This builds only packages that are not yet in the local Conan cache
* `-m /workdir/EBxelor-2020.12/config/valeria/s32g/manifests/buildmanifest_linuxbuild.xml`: the build manifest that shall be used.
* `-p /workdir/EBxelor-2020.12/config/valeria/s32g/profiles`: the folder to the profiles
* `-r /workdir/EBxelor-2020.12/pkg`: the folder of all recipes, sub-folders are also parsed for recipes
* `-cr eb_core-devdrops`: the name of the Artifactory repository, known by `conan remote`. In EB xelor development we use a repository called `eb_core-devdrops` for development work.
* `-ccr EBxelor/2020.12:eb_core-releases`: this instructs Valeria to copy existing (equal) packages from user `EBxelor`, channel `2020.12`, repo `eb_core-releases`. In EB xelor development we fill this user, channel, and repository with our releases.
* `-cdd`: this instructs Valeria to delete an existing build directory.
* `your_user valeria-test`: the Conan user and channel

In subsequent calls, the parameter `-ccr` can be omitted.
It is used to initially populate the new channel `user/valeria-test`.

If you want to upload the produced packages to the remote repository, then add the option `-n 0`.

===== Windows
To build the packages that require a Windows build machine, we assume that the sources are placed in a folder `./EBxelor-2020.12`.
We create a working folder for Valeria parallel to it `./valeria-build`.

We also assume that we call the build inside a bash shell, e.g. git bash or cygwin.

For detailed instructions how to setup the windows build environment, please refer to chapter <<EBtresos>>.

....
cd valeria-build
python ../EBxelor-2020.12/tools/valeria/valeria.py -b missing -M build \
-m ../EBxelor-2020.12/config/valeria/s32g/manifests/\
buildmanifest_windowsbuild.xml \
-p ../EBxelor-2020.12/config/valeria/s32g/profiles \
-r ../EBxelor-2020.12/pkg \
-cr eb_core-devdrops \
-ccr EBxelor/2020.12:eb_core-releases \
-cdd \
your_user valeria-test
....

The arguments are the same as in the Linux builds and described above.


===== Download a release
You can also download a release by calling valeria directly with the EB xelor release user, channel, and repository.
Example to download all packages that are built in Linux, for the S32G SoC and release `2020.12`:
....
mkdir -p /workdir/valeria/s32g
cd /workdir/valeria/s32g
/workdir/EBxelor-2020.12/tools/valeria/valeria.py -b missing -M build \
-m /workdir/EBxelor-2020.12/config/valeria/s32g/manifests/\
buildmanifest_linuxbuild.xml \
-p /workdir/EBxelor-2020.12/config/valeria/s32g/profiles \
-r /workdir/EBxelor-2020.12/pkg \
-cr eb_core-releases \
-cdd \
EBxelor 2020.12
....
In this case we omit the `-ccr` command. The conan packages will not be copied to a separate conan user/channel.
Instead you will use user `EBxelor` and channel `2020.12`, as well as repository `eb_core-releases`.
You will not be able to upload your packages to Artifactory, as the `eb_core-releases` repository is reserved
for EB xelor releases.

[TIP]
====
If your local source code (directory `/workdir/EBxelor-2020.12`) is identical to the release, e.g. `EBxelor 2020.12`, 
then there is no rebuild executed of any package. Instead the packages are directly downloaded from Artifactory.

If you have a local change in a recipe, then this recipe will be rebuilt.
====

Example to download all packages that are built in Windows, for the S32G SoC and release `2020.12`
(please refer to chapter <<EBtresos>> for conan configuration in Windows):
....
cd valeria-build
python ../EBxelor-2020.12/tools/valeria/valeria.py -b missing -M build \
-m ../EBxelor-2020.12/config/valeria/s32g/manifests/\
buildmanifest_windowsbuild.xml \
-p ../EBxelor-2020.12/config/valeria/s32g/profiles \
-r ../EBxelor-2020.12/pkg \
-cr eb_core-releases \
-cdd \
EBxelor 2020.12
....

[TIP]
====
If you do not want to rebuild the software, you can also download the binaries that have been built in Linux by running Valeria in Windows and vice versa.
Just replace the `buildmanifest_windowsbuild.xml` by `buildmanifest_linuxbuild.xml`. This way you can download all artifacts for the target in the same environment.
====